### ISSUE TITLE
Commit action not available

### ISSUE THREAD

**Issue by EpocDotFr** [ATLauncher/Translations#1]
The commit action [as described in the README](https://github.com/ATLauncher/Translations/blob/master/launcher/v3/README.md#how-to-translate) is not available (for me at last). I checked on different pages (i.e on the French translation page, the main translation project and on the root page of the web app).

**Comment by RyanTheAllmighty** [comment]
Yeah this system is new to me. I'm guessing only I have access to that.

I'll do some checking and see what the actual proper process is to 'commit' these changes and get back to you.

Thanks again for helping out :)

**Comment by EpocDotFr** [comment]
Okay :)

You're welcome!

**Comment by RyanTheAllmighty** [comment]
Alright so there shouldn't be a need to commit, I'll make the changes directly available in the launcher (not the current version, a future version coming soon) and send the commits to GitHub every hour.

Seems to be the best solution.

I'll most likely be adding in these translations from this new system into the upcoming launcher version over the next couple of days, so I'll edit the README with information on that and a link to the test version once done
